from quickfind import quickfind

newQF = quickfind(10)
print(newQF.id)
newQF.union(4,3)
print(newQF.id)
newQF.union(3,8)
print(newQF.find(5,6))
newQF.union(6,5)
print(newQF.id)
newQF.union(9,4)
print(newQF.find(1,9))
newQF.union(8,9)
print(newQF.id)
newQF.union(8,9)
newQF.union(2,1)
newQF.union(7,6)
newQF.union(5,4)
print(newQF.id)

